name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: create keystore file, fill key
      run: |
        mkdir -p $HOME/.sign/
        CURPWD=$(pwd)
        echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > keystore.jks
        echo "" > ~/.sign/signing.properties
        echo "keystore=${CURPWD}/keystore.jks" >> ~/.sign/signing.properties
        echo "store.pass=${{ secrets.KEY_STORE_PASSWORD }}" >> ~/.sign/signing.properties
        echo "key.alias=${{ secrets.ALIAS }}" >> ~/.sign/signing.properties
        echo "key.pass=${{ secrets.KEY_PASSWORD }}" >> ~/.sign/signing.properties
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Test app on apptest.ai
      uses: forcemax/apptestai-test@v1
      with:
        access_key: ${{ secrets.APPTEST_AI_ACCESS_KEY }}
        project_id: 1111 
        binary_path: app/build/outputs/apk/prod/release/app-prod-release.apk
        use_vo: false
        time_limit: 5
        login_id: ${{ secrets.APP_LOGIN_ID }}
        login_pw: ${{ secrets.APP_LOGIN_PW }}
